import os
content = []
content.append('@keyframes flowGrad {')
content.append('    0% { background-position: 0% 50%; }')
content.append('    50% { background-position: 100% 50%; }')
content.append('    100% { background-position: 0% 50%; }')
content.append('}')
content.append('.btn-flow {')
content.append('    background: linear-gradient(135deg, #f06292, #ce93d8, #ec407a, #ba68c8, #f06292);')
content.append('    background-size: 300% 300%;')
content.append('    animation: flowGrad 4s ease infinite;')
content.append('    color: white; border: none; border-radius: 24px;')
content.append('    padding: 12px 28px; font-size: 15px; font-weight: 600;')
content.append('    cursor: pointer; transition: all 0.3s ease;')
content.append('    box-shadow: 0 4px 16px rgba(236,64,122,0.30);')
content.append('    position: relative; overflow: hidden;')
content.append('}')
content.append('.btn-flow:hover { transform: translateY(-2px); box-shadow: 0 8px 28px rgba(236,64,122,0.45); }')
content.append('.btn-flow:active { transform: translateY(0) scale(0.97); }')
content.append('.btn-flow::after {')
content.append('    content: "";')
content.append('    position: absolute; inset: -2px;')
content.append('    border-radius: 26px;')
content.append('    background: linear-gradient(135deg, rgba(255,255,255,0.3), transparent, rgba(255,255,255,0.2));')
content.append('    opacity: 0; transition: opacity 0.4s;')
content.append('}')
content.append('.btn-flow:hover::after { opacity: 1; }')
content.append('.input-glass {')
content.append('    background: rgba(255,255,255,0.20);')
content.append('    backdrop-filter: blur(8px);')
content.append('    border: 1.5px solid rgba(255,255,255,0.35);')
content.append('    border-radius: 12px; padding: 14px 16px;')
content.append('    font-size: 15px; outline: none; transition: all 0.3s;')
content.append('    color: var(--text-primary); width: 100%;')
content.append('}')
content.append('.input-glass:focus {')
content.append('    border-color: var(--pink-400);')
content.append('    background: rgba(255,255,255,0.35);')
content.append('    box-shadow: 0 0 0 3px rgba(240,98,146,0.12);')
content.append('}')
content.append('.input-glass::placeholder { color: var(--text-muted); }')
path = r'D:\111网安学习\menstrual-tracker\frontend\src\assets\pink-theme.css'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(content))
print('CSS part 3 written')
