import os
content = []
content.append('.bottom-nav {')
content.append('    position: fixed; bottom: 0; left: 50%;')
content.append('    transform: translateX(-50%); width: 100%; max-width: 420px;')
content.append('    background: rgba(255,255,255,0.22);')
content.append('    backdrop-filter: blur(20px);')
content.append('    -webkit-backdrop-filter: blur(20px);')
content.append('    border-top: 1px solid rgba(255,255,255,0.35);')
content.append('    display: flex; justify-content: space-around;')
content.append('    padding: 6px 0 env(safe-area-inset-bottom);')
content.append('    z-index: 100; border-radius: 20px 20px 0 0;')
content.append('    box-shadow: 0 -4px 20px rgba(236,64,122,0.06);')
content.append('}')
content.append('.nav-item {')
content.append('    display: flex; flex-direction: column; align-items: center;')
content.append('    padding: 4px 12px; cursor: pointer; transition: all 0.2s;')
content.append('    text-decoration: none; color: var(--text-muted); font-size: 11px;')
content.append('}')
content.append('.nav-item.active { color: var(--pink-500); }')
content.append('.nav-item .icon { font-size: 22px; margin-bottom: 2px; transition: transform 0.2s; }')
content.append('.nav-item.active .icon { transform: scale(1.15); }')
content.append('.header-bar {')
content.append('    display: flex; align-items: center; justify-content: space-between;')
content.append('    padding: 16px 20px; position: sticky; top: 0; z-index: 50;')
content.append('}')
content.append('.header-title {')
content.append('    font-size: 20px; font-weight: 700;')
content.append('    background: linear-gradient(135deg, var(--pink-500), var(--purple-400));')
content.append('    -webkit-background-clip: text; -webkit-text-fill-color: transparent;')
content.append('}')
content.append('.chip-group { display: flex; flex-wrap: wrap; gap: 8px; margin-bottom: 4px; }')
content.append('.chip {')
content.append('    padding: 6px 14px; border-radius: 16px; font-size: 13px;')
content.append('    background: rgba(255,255,255,0.18);')
content.append('    backdrop-filter: blur(4px);')
content.append('    color: var(--text-secondary); cursor: pointer; transition: all 0.2s;')
content.append('    border: 1px solid rgba(255,255,255,0.25);')
content.append('}')
content.append('.chip.active {')
content.append('    background: linear-gradient(135deg, #f06292, #ba68c8);')
content.append('    color: white; border-color: transparent;')
content.append('}')
path = r'D:\111网安学习\menstrual-tracker\frontend\src\assets\pink-theme.css'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(content))
print('CSS part 5 written')
