import os
content = []
content.append('@keyframes float {')
content.append('    0%, 100% { transform: translateY(0) rotate(0deg); }')
content.append('    33% { transform: translateY(-8px) rotate(2deg); }')
content.append('    66% { transform: translateY(4px) rotate(-1deg); }')
content.append('}')
content.append('@keyframes fade-in-up {')
content.append('    from { opacity: 0; transform: translateY(20px); }')
content.append('    to { opacity: 1; transform: translateY(0); }')
content.append('}')
content.append('.animate-float { animation: float 3s ease-in-out infinite; }')
content.append('.animate-fade-in-up { animation: fade-in-up 0.5s ease-out both; }')
content.append('.page-enter-active, .page-leave-active { transition: all 0.3s ease; }')
content.append('.page-enter-from { opacity: 0; transform: translateX(20px); }')
content.append('.page-leave-to { opacity: 0; transform: translateX(-20px); }')
content.append('.gradient-text {')
content.append('    background: linear-gradient(135deg, var(--pink-500), var(--purple-400));')
content.append('    -webkit-background-clip: text; -webkit-text-fill-color: transparent;')
content.append('    background-clip: text;')
content.append('}')
content.append('.mobile-container {')
content.append('    max-width: 420px; margin: 0 auto; padding: 16px;')
content.append('    padding-bottom: 80px; min-height: 100vh; position: relative; z-index: 1;')
content.append('}')
path = r'D:\111网安学习\menstrual-tracker\frontend\src\assets\pink-theme.css'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(content))
print('CSS part 4 written')
