import os
content = []
content.append('* { margin: 0; padding: 0; box-sizing: border-box; }')
content.append('body {')
content.append('    font-family: -apple-system, BlinkMacSystemFont, PingFang SC, Microsoft YaHei, sans-serif;')
content.append('    -webkit-font-smoothing: antialiased;')
content.append('    min-height: 100vh;')
content.append('    background: linear-gradient(-45deg, #fce4ec, #f3e5f5, #f8bbd0, #e1bee7, #fce4ec, #fff3e0);')
content.append('    background-size: 400% 400%;')
content.append('    animation: bgFlow 18s ease infinite;')
content.append('    color: var(--text-primary);')
content.append('}')
content.append('@keyframes bgFlow {')
content.append('    0% { background-position: 0% 50%; }')
content.append('    25% { background-position: 100% 0%; }')
content.append('    50% { background-position: 100% 100%; }')
content.append('    75% { background-position: 0% 100%; }')
content.append('    100% { background-position: 0% 50%; }')
content.append('}')
content.append('.glass {')
content.append('    background: var(--glass-bg);')
content.append('    backdrop-filter: blur(16px);')
content.append('    -webkit-backdrop-filter: blur(16px);')
content.append('    border: 1px solid var(--glass-border);')
content.append('    border-radius: 16px;')
content.append('    box-shadow: var(--glass-shadow);')
content.append('    transition: all 0.3s ease;')
content.append('}')
content.append('.glass:active { transform: scale(0.97); }')
content.append('')
path = r'D:\111网安学习\menstrual-tracker\frontend\src\assets\pink-theme.css'
with open(path, 'a', encoding='utf-8') as f:
    f.write('\n'.join(content))
print('CSS part 2 written')
