server {
    listen 80;
    # 域名备案可用后，可恢复为 www.moyoo.asia moyoo.asia
    server_name 42.194.244.111 www.moyoo.asia moyoo.asia;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    http2 on;
    # 域名备案可用后，可恢复为 www.moyoo.asia moyoo.asia
    server_name 42.194.244.111 www.moyoo.asia moyoo.asia;

    root /usr/share/nginx/html;
    index index.html;
    client_max_body_size 20m;

    ssl_certificate /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        try_files $uri $uri/ /admin/index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
